name: Installing Python
on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest
        py-version:
          - "3.10"
          - "3.11"
          - "3.12"
        exclude:
          - os: windows-latest  # Exclude Windows completely from the matrix

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
