name: System Information Check

on: push

jobs:
  system-info:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        shell: [bash, sh, zsh]
        exclude:
          - os: windows-latest
            shell: zsh  # Exclude Zsh on Windows (unsupported)

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display System Information
        shell: ${{ matrix.shell }}
        run: |
          echo "Running on OS: ${{ matrix.os }} with shell: ${{ matrix.shell }}"
          echo "OS Information:"
          uname -a
          echo "Current Date & Time:"
          date
          echo "System Uptime:"
          uptime
