name: Matrix Strategy Testing
on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        shell: [bash, sh, zsh]
      exclude:
        - os: windows-latest
          shell: zsh  # Exclude Zsh on Windows (unsupported)

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display System Information
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using shell: ${{ matrix.shell }}"

      - name: Execute Bash Script
        shell: ${{ matrix.shell }}
        run: |
          echo "Hello from ${{ matrix.shell }} on ${{ matrix.os }}"
          date  # Display the current date
