name: Install Node.js Without package.json
on: push

jobs:
  install-node:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16, 18, 20]
      exclude:
        - os: windows-latest
          node-version: 14  # Exclude Node.js 14 on Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify Node.js Installation
        run: |
          echo "Node.js Version:"
          node --version
          echo "NPM Version:"
          npm --version
