name: Matrix Strategy Testing
on: push

jobs:
  test:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, macos-latest, windows-latest]
      exclude:
        - node-version: 14
          os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run macOS-specific step
        if: runner.os == 'macOS'
        run: echo "This step runs only on macOS"
