name: Matrix Strategy - Install Python (Excluding Python 3.8 on Windows)

on: push

jobs:
  install-python:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]
        exclude:
          - os: windows-latest
            python-version: 3.8  # Exclude Python 3.8 on Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Python Installation
        run: |
          echo "Python version installed:"
          python --version
