name: Echo Secret
on: [push]  # Triggers the workflow on a push to the repository.

jobs:
  display-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        run: echo "The secret is ${{ secrets.SECRET }}"
